### ISSUE TITLE
Put several ids in cleave()

### ISSUE THREAD

**Issue by etiennebacher** [JohnCoene/sever#1]
Here's an example:
```
library(shiny)
library(sever)

ui <- fluidPage(
  use_sever(),
  tableOutput("table"),
  plotOutput("plot"),
  uiOutput("thing")
)

server <- function(input, output){
  cleave("hey", ids = "table")
  
  output$table <- renderTable({
    error
  })
  
  output$thing <- renderUI({
    p(error)
  })
  
  output$plot <- renderPlot({
    plot(error)
  })
}

shinyApp(ui, server)
```
What if I want to display the same message for the table and the plot but not for the `uiOutput`? I tried to use `c()` and `list()` in the argument `ids` of `cleave()` but no success.

Is there a way to put a list of ids in `cleave()`?

**Comment by JohnCoene** [comment]
Hi Etienne,

Passing multiple ids to `cleave` was always meant to work hence the argument is named `ids` (plural): I'm afraid you just stumbled upon a bug. I just pushed a fix. Would you mind reinstalling from Github and let me know if it works for you?

```r
library(shiny)
devtools::load_all()

ui <- fluidPage(
  use_sever(),
  tableOutput("table"),
  plotOutput("plot"),
  uiOutput("thing")
)

server <- function(input, output){
  cleave("hey", ids = c("table", "plot", "ids"))
  
  output$table <- renderTable({
    error
  })
  
  output$thing <- renderUI({
    p(error)
  })
  
  output$plot <- renderPlot({
    plot(error)
  })
}

shinyApp(ui, server)
```

**Comment by etiennebacher** [comment]
Perfect, it works now :+1:
