### ISSUE TITLE
using sever with session$allowReconnect()

### ISSUE THREAD

**Issue by tanho63** [JohnCoene/sever#11]
Hi John - have long been a fan of sever! I've been experimenting with session$allowReconnect() lately and have been wondering if there was a way to use sever with it rather than using location.reload() as per sever_default(). At the moment it seems to correctly fire the page but it doesn't remove the sever screen, e.g.

https://streamable.com/gbjute

<details><summary> reprex code </summary>

```r
library(shiny)
library(sever)

ui <- fluidPage(
  useSever(),
  h1("Hello")
)

server <- function(input, output, session) {
  sever(
    html = tagList(
           tags$button("Reconnect",onclick = "Shiny.shinyapp.reconnect();", href = "#")
    )
  )
  session$allowReconnect("force")
}

shinyApp(ui, server)
```

</details>

I `think` the correct implementation might be to add a ?callback? or something that watches the `Shiny.shinyapp.reconnect()` action and then clears the sever screen? (My JS-fu is not very strong...)

**Comment by tanho63** [comment]
I feel like this is a poor implementation that could be much improved by just handling in JS:

```r
library(shiny)
library(sever)
library(shinyjs)

ui <- fluidPage(
  useSever(),
  useShinyjs(),
  h1("Hello")
  
)

server <- function(input, output, session) {
  sever(
    html = tagList(
      div(
        id = "sever-screen",
        tags$button("Reconnect",onclick = "Shiny.shinyapp.reconnect();", href = "#")
      )
    )
  )
  observeEvent(TRUE, shinyjs::hide("sever-screen"),ignoreInit = FALSE, ignoreNULL = FALSE)
  
  session$allowReconnect("force")
}

shinyApp(ui, server)
```

**Comment by JohnCoene** [comment]
I can include that in the package, good idea.

Does that work?

```r
library(shiny)
library(sever)
library(shinyjs)

script <- HTML(
  "() => {
    $('#shiny-disconnected-overlay').hide();
    Shiny.shinyapp.reconnect();
  }"
)

ui <- fluidPage(
  useSever(),
  tags$head(
    tags$script(
      script
    )
  ),
  h1("Hello"),
  actionButton(
    "disconnect",
    "Disconnect"
  )
)

server <- function(input, output, session) {
  sever(
    html = tagList(
      div(
        id = "sever-screen",
        tags$button(
          "Reconnect",
          onclick = "reconnect()", 
          href = "#"
        )
      )
    )
  )
  
  session$allowReconnect()

  observeEvent(input$disconnect, {
    session$close()
  })
}

shinyApp(ui, server)
```

**Comment by tanho63** [comment]
Hmm, having trouble with this example, is the script/function supposed to be `reconnect() =>...`?

**Comment by JohnCoene** [comment]
Yes, it should hide the disconnected screen and reconnect with `Shiny.shinyapp.reconnect();`
I assumed the code you had worked, did it not?

I always had issues testing this as, to the best of my knowledge, reconnect does not work locally

**Comment by tanho63** [comment]
I think you can use session$allowReconnect("force") locally provided you open the app in your browser and then either console-exit or button-exit as shown. 

The reprex you shared calls `reconnect()` in the onclick arg but I don't think the JS script defines `reconnect()` properly

**Comment by JohnCoene** [comment]
I don't see anything wrong with the `reconnect` function assuming `Shiny.shinyapp.reconnect();` actually reconnects, let me know if you see something wrong.

But I don't think this works properly locally, does the app below work?

```r
library(shiny)

ui <- fluidPage(
  actionButton(
    "disconnect",
    "Disconnect"
  ) 
)

server <- function(input, output, session) {
  session$allowReconnect("force")
  
  observeEvent(input$disconnect, {
    session$close()
  })
}

shinyApp(ui, server)
```

It constantly attempts to reconnect but never manages to, that may be something that happens locally. 
If that's how it works remotely we can change the code, there's no need for a button.

```r
library(shiny)
library(sever)

script <- HTML(
  "$(document).on('shiny:connected', (e) => {
    $('#shiny-disconnected-overlay').hide();
  });"
)


ui <- fluidPage(
  useSever(),
  tags$head(
    tags$script(
      script
    )
  ),
  h1("Hello"),
  actionButton(
    "disconnect",
    "Disconnect"
  )
)

server <- function(input, output, session) {
  sever(
    html = tagList(
      div(
        id = "sever-screen",
        p("We don't need a button it just fires")
      )
    )
  )
  
  session$allowReconnect("force")

  observeEvent(input$disconnect, {
    session$close()
  })
}

shinyApp(ui, server)
```

It's similar to the first snippet of code I shared, we can see the underlying content of the app flash before the reconnection seemingly fails and attempts again.

**Comment by tanho63** [comment]
Ooh, that JS chunk is basically exactly what I was trying to do with

`observeEvent(TRUE, shinyjs::hide("sever-screen"),ignoreInit = FALSE, ignoreNULL = FALSE)`

earlier! I wonder if that can just be included in the basic JS that's added by `useSever()`?

**Comment by tanho63** [comment]
re: your question about the reconnect function: this is what I noticed earlier when I tried to hit the button

![image](https://user-images.githubusercontent.com/38083823/164082829-a02f777a-e424-4aa2-a747-0958e50f55eb.png)

**Comment by JohnCoene** [comment]
Yes, didn't think of including this by default. It should be good now.

One change though is that the default overlay should be removed instead of hidden (`$('#shiny-disconnected-overlay').remove()`)

**Comment by JohnCoene** [comment]
On the button, indeed there was an error.
It should have been.

```r
script <- HTML(
  "const reconnect = () => {
    $('#shiny-disconnected-overlay').hide();
    Shiny.shinyapp.reconnect();
  }"
)
```

**Comment by JohnCoene** [comment]
Is a button necessary though? Is the automatic reconnect just a local thing or also applies when deployed?

**Comment by tanho63** [comment]
Unsure yet. I’ll open a new issue if I think the button trigger is helpful, I haven’t managed to test on the actual shiny server app yet

**Comment by JohnCoene** [comment]
Thank you Tan!

**Comment by tanho63** [comment]
![image](https://user-images.githubusercontent.com/38083823/164128766-f4c36ecc-962a-441c-a929-480b12f98391.png)
hmm, ran into some issues implementing and was debugging, it seems like it didn't like the `(e) => {}` syntax here but I was able to replace with `function(e) {}` and it worked okay

**Comment by JohnCoene** [comment]
That looks like an encoding issue.
Did you wrap the JavaScript code in `shiny::HTML`?
As long as it works now

**Comment by tanho63** [comment]
Oh. No. lmaoo thank you
