### ISSUE TITLE
Box=TRUE still no box bs4dash package

### ISSUE THREAD

**Issue by HugoGit39** [JohnCoene/sever#18]
Hi!

Great package!

I do have an issue: somehow if `box=T`...there is still no box. My code is huge so it is a bit difficult to add it here

But so does this also happened to you @JohnCoene before in certain code? Is it wise to share the packages which I use?

FYI in the provided sample code it works, so I guess there is a conflict somewhere in my code

**Comment by HugoGit39** [comment]
I kinda debugged it...it looks like it has to do with the bs4dash package:

```
ui <- dashboardPage(
  header = dashboardHeader(),
  sidebar = dashboardSidebar(disable = T),
  body = bs4DashBody(
  useSever(),
  h1("sever")
  )
)

server <- function(input, output){
  sever(bg_color = "#DDDDDD75", color = "black", box = T)

}

shinyApp(ui, server)
```

**Comment by HugoGit39** [comment]
Hi @JohnCoene do you think this can be resolved anytime soon? Or more for the long run?

**Comment by JohnCoene** [comment]
I just pushed a fix, can you reinstall and try again?

**Comment by HugoGit39** [comment]
I reinstalled it but still nog box

**Comment by JohnCoene** [comment]
From your example

![image](https://github.com/JohnCoene/sever/assets/7833796/eeef5cad-44b6-4a43-afc5-04dba03972fc)

Did you reinstall, restart R, rerun your example?

**Comment by HugoGit39** [comment]
Thats interesting, I did yes..re-installed it via install_github....lemme try it again

**Comment by HugoGit39** [comment]
Whoops, I see now that I received an error re-installing it 5 min ago...re-did it and works!! Thx!

**Comment by HugoGit39** [comment]
When will you push the update to CRAN? Would love to use it in my app using a docker file

**Comment by JohnCoene** [comment]
It's on its way to CRAN

**Comment by HugoGit39** [comment]
Hi John

So it all works when I test my Shiny app locally...however when I dockerize my app it still doesnt show up. Also when I use Shiny Server Open SOurce and I reinstall the package it still doesnt show...any ide awhy?
