### ISSUE TITLE
Applying `cleave()` style to `validate()` messages

### ISSUE THREAD

**Issue by jonmcalder** [JohnCoene/sever#3]
A followup which arises from #2, is whether the same `cleave()` style could be applied to `validate()` messages.

i.e. whether the message(s) supplied to `need()` within `validate()` could be passed on to `cleave()` instead of the current option (as I understand it) to either cleave everything or allow silent errors to be displayed natively by shiny.

This is not necessarily what I had in mind when raising #2, just thought of it afterwards now in the interest of consistent styling. Since it seems like more of a wishlist item and probably needs to be thought through more (assuming it's even feasible somehow), I figured it warranted a separate issue.

**Comment by JohnCoene** [comment]
Yes I agree. I had not though of the `need` messages but it's a good point: one would probably want to apply two different styles depending on the "error" type, I suppose in a sense `need` are more user-friendly messages than errors: different styles make sense.

I just have to think of a convenient API to do so. Perhaps cleave should only tackle hard errors and another function (very similar) would deal with the `need` messages.

**Comment by JohnCoene** [comment]
@jonmcalder any good idea for a new function name for this? Keeping in mind that the package does not come with sensible function names: `sever` should be something like `on_disconnect` and `cleave` should be `on_error` then we could have `on_need` but hey we're a creative bunch :D

**Comment by jonmcalder** [comment]
Haha, thanks for asking. How about `chisel`?

**Comment by JohnCoene** [comment]
Sounds good!

**Comment by JohnCoene** [comment]
I added `chisel` :partying_face: 

```r
library(shiny)
library(sever)

ui <- fluidPage(
  use_sever(),
  fluidRow(
    selectInput("required_input", "Required input",
      choices = c("Red pill", "Blue pill"), 
      multiple = TRUE
    ),
    uiOutput("thing")
  )
)

server <- function(input, output){
  cleave(silent_errors = FALSE)
  chisel(color = "black", center_horizontal = FALSE)
  
  # will generate errors
  output$thing <- renderUI({
    validate(need(input$required_input, "Required input is required 😂"))
    if("Red pill" %in% input$required_input) {
      h1("Good choice!")
    } else {
      stop("A regrettable decision.")
    }
  })
  
}

shinyApp(ui, server)
```

**Comment by jonmcalder** [comment]
Awesome! 🎉 🍾
